baseurl = "/"
title = "Mobu's Journal"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Mubasser Kamal"
relativeURLs = true
uglyURLs = false
pygmentsUseClasses=true
highlightjsVersion = "9.18.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["dart"]
highlightjsTheme = "dracula"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Mubasser Kamal"
    #profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Journal"
    description = "Collection of all things learned"
    github = "https://github.com/mobu"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    #twitter = "https://twitter.com/XXX"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #facebook = "https://www.facebook.com/username"
    #email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 3